# -*- coding: utf-8 -*-
"""week.a108260018高佳豪.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15rkzibGgzyCzxdjAUKh5gjoQG4ecizM0
"""

print(“Hello World”)